# Generated by Django 5.2.3 on 2025-06-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='image_data',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='image_urls',
        ),
    ]
