# Generated by Django 5.2.3 on 2025-06-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_image_data_chatmessage_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSummarize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='chatbot.chatsession')),
            ],
        ),
    ]
