chatsessions_data = [
    {"title": "Session 1", "owner_id": 1},
    {"title": "Session 2", "owner_id": 1},
    {"title": "Session 3", "owner_id": 1},
    {"title": "Session 4", "owner_id": 1},
    {"title": "Session 5", "owner_id": 1},
    {"title": "Session 6", "owner_id": 1},
    {"title": "Session 7", "owner_id": 1},
    {"title": "Session 8", "owner_id": 1},
    {"title": "Session 9", "owner_id": 1},
    {"title": "Session 10", "owner_id": 1},
    {"title": "Session 11", "owner_id": 1},
    {"title": "Session 12", "owner_id": 1},
    {"title": "Session 13", "owner_id": 1},
    {"title": "Session 14", "owner_id": 1},
    {"title": "Session 15", "owner_id": 1},
    {"title": "Session 16", "owner_id": 1},
    {"title": "Session 17", "owner_id": 1},
    {"title": "Session 18", "owner_id": 1},
    {"title": "Session 19", "owner_id": 1},
    {"title": "Session 20", "owner_id": 1},
]
